{% set version = "1.0.2q" %}

package:
  name: openssl
  version: {{ version }}

source:
  url: http://www.openssl.org/source/openssl-{{ version }}.tar.gz
  sha256: 5744cfcbcec2b1b48629f7354203bc1e5e9b5466998bbccc5b5fcde3b18eb684

build:
  number: 0
  no_link: lib/libcrypto.so.1.0.0        # [linux]
  no_link: lib/libcrypto.1.0.0.dylib     # [osx]
  has_prefix_files:                      # [unix]
    - bin/c_rehash                       # [unix]
    - include/openssl/opensslconf.h      # [unix]
    - lib/pkgconfig/libcrypto.pc         # [unix]
    - lib/pkgconfig/libssl.pc            # [unix]
    - lib/pkgconfig/openssl.pc           # [unix]
  run_exports:
    - {{ pin_subpackage('openssl', max_pin='x.x.x') }}
  ignore_prefix_files:
    - lib/libcrypto.so.1.0.0             # [linux]

requirements:
  build:
    - {{ compiler('c') }}
    - yasm               # [win32]
    - perl
    - make               # [unix]
  run:
    - ca-certificates

test:
  commands:
    - touch checksum.txt
    - openssl sha256 checksum.txt

about:
  home: http://www.openssl.org/
  license: Apache-style (http://www.openssl.org/source/license.html)
  license_family: Apache
  license_file: LICENSE
  summary: OpenSSL is an open-source implementation of the SSL and TLS protocols
